// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu9Jl6epiQccXge6AB-i8oQmpKF8L95IE',
    appId: '1:985817775450:web:37855afbf9b06ff7594763',
    messagingSenderId: '985817775450',
    projectId: 'startupanalysis-67d42',
    authDomain: 'startupanalysis-67d42.firebaseapp.com',
    storageBucket: 'startupanalysis-67d42.appspot.com',
    measurementId: 'G-MZ1WEKX497',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5i_9dUgfUzO3JtK7DHnpRjgEjrxLFJaE',
    appId: '1:985817775450:android:910eec062f2ae34d594763',
    messagingSenderId: '985817775450',
    projectId: 'startupanalysis-67d42',
    storageBucket: 'startupanalysis-67d42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF7mzx1VgyUuua8Tf94LNXnRV0B8V5i2g',
    appId: '1:985817775450:ios:5c5fe8f512d12280594763',
    messagingSenderId: '985817775450',
    projectId: 'startupanalysis-67d42',
    storageBucket: 'startupanalysis-67d42.appspot.com',
    iosClientId: '985817775450-ciqbpa6t3j01hdn8dhafbaa768j1d43m.apps.googleusercontent.com',
    iosBundleId: 'com.example.startup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF7mzx1VgyUuua8Tf94LNXnRV0B8V5i2g',
    appId: '1:985817775450:ios:5c5fe8f512d12280594763',
    messagingSenderId: '985817775450',
    projectId: 'startupanalysis-67d42',
    storageBucket: 'startupanalysis-67d42.appspot.com',
    iosClientId: '985817775450-ciqbpa6t3j01hdn8dhafbaa768j1d43m.apps.googleusercontent.com',
    iosBundleId: 'com.example.startup',
  );
}
