import 'startup.dart';

final List<Startup> startupData = [
  Startup(
    id: 1,
    name: 'BYJU’S',
    industry: 'E-Tech',
    subVertical: 'E-learning',
    city: 'Bengaluru',
    investors: 'Tiger Global Management',
    investmentType: 'Private Equity Round',
    amount: 2000000000,
  ),
  Startup(
    id: 2,
    name: 'Shuttl',
    industry: 'Transportation',
    subVertical: 'App based shuttle service',
    city: 'Gurgaon',
    investors: 'Susquehanna Growth Equity',
    investmentType: 'Series C',
    amount: 8048394,
  ),
  Startup(
    id: 3,
    name: 'Mamaearth',
    industry: 'E-commerce',
    subVertical: 'Retailer of baby and toddler products',
    city: 'Bengaluru',
    investors: 'Sequoia Capital India',
    investmentType: 'Series B',
    amount: 18358860,
  ),
  Startup(
    id: 4,
    name: 'WealthBucket',
    industry: 'FinTech',
    subVertical: 'Online Investment',
    city: 'New Delhi',
    investors: 'Vinod Khatumal',
    investmentType: 'Pre-series A',
    amount: 300000,
  ),
  Startup(
    id: 5,
    name: 'Fashor',
    industry: 'Fashion and Apparel',
    subVertical: 'Embroiled Clothes For Women',
    city: 'Mumbai',
    investors: 'Sprout Venture Partners',
    investmentType: 'Seed Round',
    amount: 1800000,
  ),
  Startup(
    id: 6,
    name: 'Pando',
    industry: 'Logistics',
    subVertical: 'Open-market, freight management platform',
    city: 'Chennai',
    investors: 'Chiratae Ventures',
    investmentType: 'Series A',
    amount: 9000000,
  ),
  Startup(
    id: 7,
    name: 'Zomato',
    industry: 'Hospitality',
    subVertical: 'Online Food Delivery Platform',
    city: 'Gurgaon',
    investors: 'Ant Financial',
    investmentType: 'Private Equity Round',
    amount: 150000000,
  ),
  Startup(
    id: 8,
    name: 'Ecozen',
    industry: 'Technology',
    subVertical: 'Agritech',
    city: 'Pune',
    investors: 'Sathguru Catalyzer Advisors',
    investmentType: 'Series A',
    amount: 6000000,
  ),
  Startup(
    id: 9,
    name: 'CarDekho',
    industry: 'E-Commerce',
    subVertical: 'Automobile',
    city: 'Gurgaon',
    investors: 'Ping An Global Voyager Fund',
    investmentType: 'Series D',
    amount: 70000000,
  ),
  Startup(
    id: 10,
    name: 'Dhruva Space',
    industry: 'Aerospace',
    subVertical: 'Satellite Communication',
    city: 'Bengaluru',
    investors: 'Mumbai Angels, Ravikanth Reddy',
    investmentType: 'Seed',
    amount: 50000000,
  )
];